### ISSUE TITLE
Doesn't run on Apple Silicon Mac

### ISSUE THREAD

**Issue by thebitstick** [nullpomino/nullpomino#78]
Tried v7.5.0 with the latest Java from java.com, 1.8.0

Tried play_slick:
![image](https://user-images.githubusercontent.com/13919134/99893759-78727800-2c47-11eb-8432-f243332794e4.png)
Log:
```
22:18:16,847 [main] INFO  NullpoMinoSlick: NullpoMinoSlick Start
22:18:17,153 [main] INFO  NullpoMinoSlick: Driver adapter:null, Driver version:null
22:18:17,265 [main] INFO  Slick: Slick Build #229
22:18:17,267 [main] INFO  Slick: LWJGL Version: 2.6
22:18:17,267 [main] INFO  Slick: OriginalDisplayMode: 2560 x 1080 x 32 @60Hz
22:18:17,267 [main] INFO  Slick: TargetDisplayMode: 640 x 480 x 0 @0Hz
JavaVM WARNING: JAWT_GetAWT must be called after loading a JVM
JavaVM WARNING: JAWT_GetAWT must be called after loading a JVM
JavaVM WARNING: JAWT_GetAWT must be called after loading a JVM
22:18:17,510 [main] ERROR Slick:
org.lwjgl.LWJGLException: Could not get the JAWT interface
	at org.lwjgl.opengl.AWTSurfaceLock.lockAndInitHandle(Native Method)
	at org.lwjgl.opengl.AWTSurfaceLock.access$100(AWTSurfaceLock.java:49)
	at org.lwjgl.opengl.AWTSurfaceLock$1.run(AWTSurfaceLock.java:88)
	at org.lwjgl.opengl.AWTSurfaceLock$1.run(AWTSurfaceLock.java:86)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.opengl.AWTSurfaceLock.privilegedLockAndInitHandle(AWTSurfaceLock.java:86)
	at org.lwjgl.opengl.AWTSurfaceLock.lockAndGetHandle(AWTSurfaceLock.java:64)
	at org.lwjgl.opengl.MacOSXCanvasPeerInfo.initHandle(MacOSXCanvasPeerInfo.java:53)
	at org.lwjgl.opengl.MacOSXDisplayPeerInfo.doLockAndInitHandle(MacOSXDisplayPeerInfo.java:56)
	at org.lwjgl.opengl.PeerInfo.lockAndGetHandle(PeerInfo.java:85)
	at org.lwjgl.opengl.MacOSXContextImplementation.create(MacOSXContextImplementation.java:47)
	at org.lwjgl.opengl.Context.<init>(Context.java:131)
	at org.lwjgl.opengl.Display.create(Display.java:859)
	at org.lwjgl.opengl.Display.create(Display.java:785)
	at org.newdawn.slick.AppGameContainer.tryCreateDisplay(AppGameContainer.java:303)
	at org.newdawn.slick.AppGameContainer.access$000(AppGameContainer.java:34)
	at org.newdawn.slick.AppGameContainer$2.run(AppGameContainer.java:368)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:349)
	at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:318)
	at mu.nu.nullpo.gui.slick.NullpoMinoSlick.main(NullpoMinoSlick.java:357)
22:18:17,521 [main] FATAL NullpoMinoSlick: Game initialize failed (SlickException)
org.newdawn.slick.SlickException: Failed to initialise the LWJGL display
	at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:379)
	at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:318)
	at mu.nu.nullpo.gui.slick.NullpoMinoSlick.main(NullpoMinoSlick.java:357)
```
Log from play_sdl:
```
22:19:29,517 [main] INFO  NullpoMinoSDL: NullpoMinoSDL Start
22:19:29,693 [main] DEBUG StateSelectModeFolderSDL: (top-level).MARATHON
22:19:29,693 [main] DEBUG StateSelectModeFolderSDL: (top-level).LINE RACE
22:19:29,693 [main] DEBUG StateSelectModeFolderSDL: (top-level).DIG RACE
22:19:29,693 [main] DEBUG StateSelectModeFolderSDL: (top-level).DIG CHALLENGE
22:19:29,693 [main] DEBUG StateSelectModeFolderSDL: (top-level).ULTRA
22:19:29,694 [main] DEBUG StateSelectModeFolderSDL: (top-level).GRADE MANIA 3
22:19:29,694 [main] DEBUG StateSelectModeFolderSDL: (top-level).SPEED MANIA 2
22:19:29,694 [main] DEBUG StateSelectModeFolderSDL: (top-level).PRACTICE
22:19:29,694 [main] DEBUG StateSelectModeFolderSDL: (top-level).GEM MANIA
22:19:29,694 [main] DEBUG StateSelectModeFolderSDL: (top-level).VS-BATTLE
22:19:29,695 [main] DEBUG StateSelectModeFolderSDL: STANDARD MODES.MARATHON
22:19:29,695 [main] DEBUG StateSelectModeFolderSDL: STANDARD MODES.MARATHON+
22:19:29,695 [main] DEBUG StateSelectModeFolderSDL: STANDARD MODES.EXTREME
22:19:29,695 [main] DEBUG StateSelectModeFolderSDL: STANDARD MODES.TECHNICIAN
22:19:29,695 [main] DEBUG StateSelectModeFolderSDL: RACE MODES.LINE RACE
22:19:29,695 [main] DEBUG StateSelectModeFolderSDL: RACE MODES.SCORE RACE
22:19:29,695 [main] DEBUG StateSelectModeFolderSDL: RACE MODES.DIG RACE
22:19:29,696 [main] DEBUG StateSelectModeFolderSDL: RACE MODES.COMBO RACE
22:19:29,696 [main] DEBUG StateSelectModeFolderSDL: RACE MODES.ULTRA
22:19:29,696 [main] DEBUG StateSelectModeFolderSDL: MANIA MODES.GRADE MANIA
22:19:29,696 [main] DEBUG StateSelectModeFolderSDL: MANIA MODES.GRADE MANIA 2
22:19:29,696 [main] DEBUG StateSelectModeFolderSDL: MANIA MODES.GRADE MANIA 3
22:19:29,696 [main] DEBUG StateSelectModeFolderSDL: MANIA MODES.SCORE ATTACK
22:19:29,697 [main] DEBUG StateSelectModeFolderSDL: MANIA MODES.SPEED MANIA
22:19:29,697 [main] DEBUG StateSelectModeFolderSDL: MANIA MODES.SPEED MANIA 2
22:19:29,697 [main] DEBUG StateSelectModeFolderSDL: MANIA MODES.GARBAGE MANIA
22:19:29,697 [main] DEBUG StateSelectModeFolderSDL: MANIA MODES.PHANTOM MANIA
22:19:29,697 [main] DEBUG StateSelectModeFolderSDL: MANIA MODES.FINAL
22:19:29,697 [main] DEBUG StateSelectModeFolderSDL: MANIA MODES.TIME ATTACK
22:19:29,697 [main] DEBUG StateSelectModeFolderSDL: MANIA MODES.GEM MANIA
22:19:29,697 [main] DEBUG StateSelectModeFolderSDL: RETRO MODES.RETRO MARATHON
22:19:29,697 [main] DEBUG StateSelectModeFolderSDL: RETRO MODES.RETRO MASTERY
22:19:29,697 [main] DEBUG StateSelectModeFolderSDL: RETRO MODES.RETRO MANIA
22:19:29,697 [main] DEBUG StateSelectModeFolderSDL: MISC MODES.SQUARE
22:19:29,698 [main] DEBUG StateSelectModeFolderSDL: MISC MODES.DIG CHALLENGE
22:19:29,698 [main] DEBUG StateSelectModeFolderSDL: MISC MODES.VS-BATTLE
22:19:29,698 [main] DEBUG StateSelectModeFolderSDL: MISC MODES.TOOL-VS MAP EDIT
22:19:29,698 [main] DEBUG StateSelectModeFolderSDL: AVALANCHE.AVALANCHE 1P (RC2)
22:19:29,698 [main] DEBUG StateSelectModeFolderSDL: AVALANCHE.AVALANCHE 1P FEVER MARATHON (RC2)
22:19:29,698 [main] DEBUG StateSelectModeFolderSDL: AVALANCHE.AVALANCHE VS-BATTLE (RC1)
22:19:29,698 [main] DEBUG StateSelectModeFolderSDL: AVALANCHE.AVALANCHE VS FEVER MARATHON (RC1)
22:19:29,698 [main] DEBUG StateSelectModeFolderSDL: AVALANCHE.AVALANCHE VS DIG RACE (RC1)
22:19:29,698 [main] DEBUG StateSelectModeFolderSDL: AVALANCHE.AVALANCHE VS BOMB BATTLE (RC1)
22:19:29,698 [main] DEBUG StateSelectModeFolderSDL: AVALANCHE.AVALANCHE-SPF VS-BATTLE (BETA)
22:19:29,698 [main] DEBUG StateSelectModeFolderSDL: PHYSICIAN.PHYSICIAN (RC1)
22:19:29,698 [main] DEBUG StateSelectModeFolderSDL: PHYSICIAN.PHYSICIAN VS-BATTLE (RC1)
22:19:29,698 [main] DEBUG StateSelectModeFolderSDL: SPF.SPF VS-BATTLE (BETA)
22:19:29,698 [main] INFO  NullpoMinoSDL: Now initializing SDL...
Native code library failed to load.
java.lang.UnsatisfiedLinkError: no sdljava in java.library.path
```
play_swing seems to work fine.

Device: Apple Mac Mini 2020, running macOS Big Sur 11.0.1, on an Apple M1.

**Comment by jpenguin** [comment]
For play_slick, I think if you "Show Package Contents" and replay the dylib files with https://github.com/yusefnapora/m1-multimc-hack/tree/master/lwjglnatives

**Comment by thebitstick** [comment]
On Oracle's standard Java 8 (x64), I get this error after placing those dylib files in the game's lib files:

```
thebitstick@Jorges-Laptop ~/A/N/C/R/Java> ./play_slick
07:48:24,650 [main] INFO  NullpoMinoSlick: NullpoMinoSlick Start
07:48:25,461 [main] WARN  NullpoMinoSlick: Cannot get driver informations
java.lang.UnsatisfiedLinkError: /Users/thebitstick/Applications/NullpoMino_7.5.0_wtf.app/Contents/Resources/Java/lib/liblwjgl.dylib: dlopen(/Users/thebitstick/Applications/NullpoMino_7.5.0_wtf.app/Contents/Resources/Java/lib/liblwjgl.dylib, 0x0001): tried: '/Users/thebitstick/Applications/NullpoMino_7.5.0_wtf.app/Contents/Resources/Java/lib/liblwjgl.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/lib/liblwjgl.dylib' (no such file)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1850)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.lwjgl.Sys$1.run(Sys.java:73)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:82)
	at org.lwjgl.Sys.<clinit>(Sys.java:99)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:130)
	at mu.nu.nullpo.gui.slick.NullpoMinoSlick.main(NullpoMinoSlick.java:233)
07:48:25,568 [main] FATAL NullpoMinoSlick: Game initialize failed (NON-SlickException)
java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.opengl.Display
	at org.newdawn.slick.AppGameContainer$1.run(AppGameContainer.java:39)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.newdawn.slick.AppGameContainer.<clinit>(AppGameContainer.java:36)
	at mu.nu.nullpo.gui.slick.NullpoMinoSlick.main(NullpoMinoSlick.java:348)
```

If I instead use Zulu17.28 (OpenJDK 17) (arm64), I get this:

```
thebitstick@Jorges-Laptop ~/A/N/C/R/Java> ./play_slick
07:50:32,880 [main] INFO  NullpoMinoSlick: NullpoMinoSlick Start
07:50:33,225 [main] WARN  NullpoMinoSlick: Cannot get driver informations
java.lang.UnsatisfiedLinkError: 'int org.lwjgl.DefaultSysImplementation.getPointerSize()'
	at org.lwjgl.DefaultSysImplementation.getPointerSize(Native Method)
	at org.lwjgl.Sys.<clinit>(Sys.java:100)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:130)
	at mu.nu.nullpo.gui.slick.NullpoMinoSlick.main(NullpoMinoSlick.java:233)
07:50:33,277 [main] FATAL NullpoMinoSlick: Game initialize failed (NON-SlickException)
java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.opengl.Display
	at org.newdawn.slick.AppGameContainer$1.run(AppGameContainer.java:39)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at org.newdawn.slick.AppGameContainer.<clinit>(AppGameContainer.java:36)
	at mu.nu.nullpo.gui.slick.NullpoMinoSlick.main(NullpoMinoSlick.java:348)
```

Device: Apple Macbook Air 2020, running macOS Monterey 12.0 Beta, on an Apple M1.

**Comment by jpenguin** [comment]
Looks like you've done everything I could think of.  Unfortunately, I was never very good with java and haven't used a Mac in over 6 years.  At least you've got the swing interface, sorry I couldn't be of more help.

**Comment by theyellowpenguin** [comment]
![image](https://user-images.githubusercontent.com/42722546/176797551-348d6596-fcb8-47fb-9135-4dfe91ae2e7e.png)
Mine instead does that. I don't know what it means but yes, this is an issue
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               JavaApplicationStub [9800]
Path:                  /Volumes/VOLUME/*/NullpoMino_7.5.0.app/Contents/MacOS/JavaApplicationStub
Identifier:            mu.nu.nullpo.gui.slick.NullpoMinoSlick
Version:               7.5.0
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-06-30 17:00:06.5324 -0700
OS Version:            macOS 12.4 (21F79)
Report Version:        12
Anonymous UUID:        59B11D59-EEA5-BEAA-C31F-D8D98E100480

Sleep/Wake UUID:       1627FF38-1EE9-4DC4-A332-60FE25D7D249

Time Awake Since Boot: 480000 seconds
Time Since Wake:       10189 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /System/Library/PrivateFrameworks/JavaApplicationLauncher.framework/Versions/A/JavaApplicationLauncher
Referenced from: /Volumes/VOLUME/*/NullpoMino_7.5.0.app/Contents/MacOS/JavaApplicationStub
Reason: tried: '/System/Library/PrivateFrameworks/JavaApplicationLauncher.framework/Versions/A/JavaApplicationLauncher' (no such file), '/Library/Frameworks/JavaApplicationLauncher.framework/Versions/A/JavaApplicationLauncher' (no such file), '/System/Library/Frameworks/JavaApplicationLauncher.framework/Versions/A/JavaApplicationLauncher' (no such file)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   Rosetta Runtime Routines	       0x100015940 ???
1   <translation info unavailable>	       0x100056ebc ???
2   dyld                          	       0x2001351d2 abort_with_payload_wrapper_internal + 80
3   dyld                          	       0x200135204 abort_with_payload + 9
4   dyld                          	       0x2000e376f dyld4::halt(char const*) + 375
5   dyld                          	       0x2000df5a5 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3995
6   dyld                          	       0x2000de4d4 start + 388

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffde19c4 0x7ff7ffddd000 + 18884
1   runtime                       	    0x7ff7ffdef460 0x7ff7ffddd000 + 74848
2   runtime                       	    0x7ff7ffdf0ed8 0x7ff7ffddd000 + 81624


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000030418f9c0   x3: 0x0000000000000124
    x4: 0x000000030418f5c0   x5: 0x0000000000000000   x6: 0x43931952b76400af   x7: 0x000000200418f5d0
    x8: 0x000000030418f5c0   x9: 0x0000000000000000  x10: 0x0000000000000124  x11: 0x000000030418f5c0
   x12: 0x0000000000000124  x13: 0x000000030418f9c0  x14: 0x0000000000000001  x15: 0x0000000000000006
   x16: 0x0000000000000209  x17: 0x0000000000000000  x18: 0x800000010807eb70  x19: 0x000000010000b000
   x20: 0x00000000000007ff  x21: 0x0000000108083fa0  x22: 0xffffffffffffffff  x23: 0x0000000100015914
   x24: 0x00000002001351d2  x25: 0x00000001000151f4  x26: 0x00000001000552c8  x27: 0x0000000000000000
   x28: 0x000000020011f0be   fp: 0x000000002c000000   lr: 0x0000000100056ebc
    sp: 0x000000010807eb70   pc: 0x0000000100015940 cpsr: 0x80001000
   far: 0x000000010863d010  esr: 0x56000080  Address size fault

Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x2000d9000 -        0x200144fff dyld (*) <b70ce1ec-b902-3852-8268-05de00bfa8d5> /usr/lib/dyld
    0x7ff7ffddd000 -     0x7ff7ffe0cfff runtime (*) <0ee8ce32-639c-316a-9551-dab9a2e0c8a5> /usr/libexec/rosetta/runtime

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1208K resident=0K(0%) swapped_out_or_unallocated=1208K(100%)
Writable regions: Total=155.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=155.2M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Rosetta Arena                     4096K        2 
Rosetta Generic                    760K      187 
Rosetta IndirectBranch              32K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack                20K        2 
Rosetta Thread Context              20K        2 
Stack                             8176K        1 
Stack Guard                       56.0M        1 
VM_ALLOCATE                       13.3M        5 
VM_ALLOCATE (reserved)               4K        1         reserved VM address space (unallocated)
__DATA                             116K        6 
__DATA_CONST                        80K        1 
__LINKEDIT                         276K        7 
__TEXT                             964K        4 
dyld private memory               1024K        1 
mapped file                        6.1G       28 
===========                     =======  ======= 
TOTAL                              6.3G      250 
TOTAL, minus reserved VM space     6.3G      250 



-----------
Full Report
-----------

{"app_name":"JavaApplicationStub","timestamp":"2022-06-30 17:00:06.00 -0700","app_version":"","slice_uuid":"b2aff5c6-4733-b518-3bce-d086a3c8a795","build_version":"7.5.0","platform":1,"bundleID":"mu.nu.nullpo.gui.slick.NullpoMinoSlick","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.4 (21F79)","incident_id":"2B9080F1-3318-4225-BB44-44107EC1367A","name":"JavaApplicationStub"}
{
  "uptime" : 480000,
  "procLaunch" : "2022-06-30 17:00:04.7577 -0700",
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir10,1",
  "procStartAbsTime" : 11661507993377,
  "coalitionID" : 64531,
  "osVersion" : {
    "train" : "macOS 12.4",
    "build" : "21F79",
    "releaseType" : "User"
  },
  "captureTime" : "2022-06-30 17:00:06.5324 -0700",
  "incident" : "2B9080F1-3318-4225-BB44-44107EC1367A",
  "bug_type" : "309",
  "pid" : 9800,
  "procExitAbsTime" : 11661549852125,
  "translated" : true,
  "cpuType" : "X86-64",
  "procName" : "JavaApplicationStub",
  "procPath" : "\/Volumes\/VOLUME\/*\/NullpoMino_7.5.0.app\/Contents\/MacOS\/JavaApplicationStub",
  "bundleInfo" : {"CFBundleVersion":"7.5.0","CFBundleIdentifier":"mu.nu.nullpo.gui.slick.NullpoMinoSlick"},
  "storeInfo" : {"deviceIdentifierForVendor":"D0485440-D20F-51E6-A52E-5F89D9815BA9","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "mu.nu.nullpo.gui.slick.NullpoMinoSlick",
  "crashReporterKey" : "59B11D59-EEA5-BEAA-C31F-D8D98E100480",
  "wakeTime" : 10189,
  "sleepWakeUUID" : "1627FF38-1EE9-4DC4-A332-60FE25D7D249",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: \/System\/Library\/PrivateFrameworks\/JavaApplicationLauncher.framework\/Versions\/A\/JavaApplicationLauncher","Referenced from: \/Volumes\/VOLUME\/*\/NullpoMino_7.5.0.app\/Contents\/MacOS\/JavaApplicationStub","Reason: tried: '\/System\/Library\/PrivateFrameworks\/JavaApplicationLauncher.framework\/Versions\/A\/JavaApplicationLauncher' (no such file), '\/Library\/Frameworks\/JavaApplicationLauncher.framework\/Versions\/A\/JavaApplicationLauncher' (no such file), '\/System\/Library\/Frameworks\/JavaApplicationLauncher.framework\/Versions\/A\/JavaApplicationLauncher' (no such file)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":4943179,"threadState":{"x":[{"value":6},{"value":1},{"value":12953647552},{"value":292},{"value":12953646528},{"value":0},{"value":4869263465172435119},{"value":137507698128},{"value":12953646528},{"value":0},{"value":292},{"value":12953646528},{"value":292},{"value":12953647552},{"value":1},{"value":6},{"value":521},{"value":0},{"value":9223372041284479856},{"value":4295012352},{"value":2047},{"value":4429725600},{"value":18446744073709551615},{"value":4295055636},{"value":8591200722,"symbolLocation":80,"symbol":"abort_with_payload_wrapper_internal"},{"value":4295053812},{"value":4295316168},{"value":0},{"value":8591110334,"symbolLocation":10,"symbol":"__abort_with_payload"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4295323324},"cpsr":{"value":2147487744},"fp":{"value":738197504},"sp":{"value":4429704048},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":4295055680,"matchesCrashFrame":1},"far":{"value":4435726352}},"frames":[{"imageOffset":4295055680,"region":"Rosetta Runtime Routines","symbolLocation":10560,"imageIndex":0},{"imageOffset":4295323324,"region":"<translation info unavailable>","imageIndex":0},{"imageOffset":377298,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":80,"imageIndex":1},{"imageOffset":377348,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":1},{"imageOffset":42863,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":1},{"imageOffset":26021,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3995,"imageIndex":1},{"imageOffset":21716,"symbol":"start","symbolLocation":388,"imageIndex":1}]},{"id":4943228,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":18884,"imageIndex":2},{"imageOffset":74848,"imageIndex":2},{"imageOffset":81624,"imageIndex":2}]}],
  "usedImages" : [
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8590823424,
    "size" : 442368,
    "uuid" : "b70ce1ec-b902-3852-8268-05de00bfa8d5",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703126376448,
    "size" : 196608,
    "uuid" : "0ee8ce32-639c-316a-9551-dab9a2e0c8a5",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  }
],
  "sharedCache" : {
  "base" : 140703254724608,
  "size" : 15220686848,
  "uuid" : "53b6853f-0bc3-33f5-be72-1aca3a188ff8"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1208K resident=0K(0%) swapped_out_or_unallocated=1208K(100%)\nWritable regions: Total=155.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=155.2M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nRosetta Arena                     4096K        2 \nRosetta Generic                    760K      187 \nRosetta IndirectBranch              32K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack                20K        2 \nRosetta Thread Context              20K        2 \nStack                             8176K        1 \nStack Guard                       56.0M        1 \nVM_ALLOCATE                       13.3M        5 \nVM_ALLOCATE (reserved)               4K        1         reserved VM address space (unallocated)\n__DATA                             116K        6 \n__DATA_CONST                        80K        1 \n__LINKEDIT                         276K        7 \n__TEXT                             964K        4 \ndyld private memory               1024K        1 \nmapped file                        6.1G       28 \n===========                     =======  ======= \nTOTAL                              6.3G      250 \nTOTAL, minus reserved VM space     6.3G      250 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000167
    },
    {
      "rolloutId" : "61301e3a61217b3110231469",
      "factorPackIds" : {
        "SIRI_FIND_MY_CONFIGURATION_FILES" : "6216ae152a40e71046e16225"
      },
      "deploymentId" : 240000016
    }
  ],
  "experiments" : [

  ]
}
}

**Comment by Kully** [comment]
@jpenguin @thebitstick Any more progress / thoughts on this?

I am also not able to run Nullpomino on Mac Silicon which is unfortunate cause I really liked the game :(

**Comment by thebitstick** [comment]
Sorry, I've already gave up on trying to play this years ago. Not really interested in trying to troubleshoot anymore.
